"""empty message

Revision ID: d5386db86e7c
Revises: 4e7dda18b19e
Create Date: 2024-10-21 13:46:37.118920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5386db86e7c'
down_revision: Union[str, None] = '4e7dda18b19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'group')
    # ### end Alembic commands ###
